name: Clarity CI
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clarinet
        uses: hirosystems/clarinet-action@v2
        with:
          args: check --manifest-path stacks-contracts/Clarinet.toml
